# Generated by Django 2.0 on 2020-06-07 03:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('star', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='star',
            options={'ordering': ['-created_time'], 'verbose_name': '收藏', 'verbose_name_plural': '收藏'},
        ),
        migrations.AddField(
            model_name='star',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='star',
            name='last_update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='上次更新时间'),
        ),
    ]
